# Generated by Django 5.2.4 on 2025-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='sub_district',
            field=models.CharField(default='ไม่ระบุ', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(default='ไม่ระบุ', max_length=100),
        ),
    ]
