# Generated by Django 5.2.4 on 2025-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_sub_district_alter_address_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(default='ไม่ระบุ', max_length=100),
        ),
    ]
