# Generated by Django 5.2.4 on 2025-09-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
