# Generated by Django 5.2.4 on 2025-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_stripe_payment_intent_order_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'บัตรเครดิต/เดบิต'), ('bank', 'โอนผ่านธนาคาร'), ('cod', 'เก็บเงินปลายทาง')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'ยังไม่ชำระ'), ('cod_pending', 'รอเก็บเงินปลายทาง'), ('paid', 'ชำระแล้ว')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันแล้ว'), ('paid', 'ชำระเงินแล้ว'), ('shipped', 'จัดส่งแล้ว'), ('completed', 'สำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
