# Generated by Django 5.2.4 on 2025-09-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'พัสดุธรรมดา'), ('express', 'ด่วน')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'รอจัดส่ง'), ('shipped', 'ส่งแล้ว'), ('delivered', 'จัดส่งสำเร็จ')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'บัตรเครดิต/เดบิต'), ('cod', 'เก็บเงินปลายทาง')], default='card', max_length=20),
        ),
    ]
