# Generated by Django 5.2.4 on 2025-09-24 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shipping_fee_order_shipping_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aftership', 'AfterShip')], default='aftership', max_length=20)),
                ('carrier_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
        ),
    ]
