# Generated by Django 5.2.4 on 2025-10-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('cod_pending', 'COD รอดำเนินการ'), ('confirmed', 'ยืนยันแล้ว'), ('paid', 'ชำระเงินแล้ว'), ('shipped', 'จัดส่งแล้ว'), ('completed', 'สำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
