# Generated by Django 5.2.4 on 2025-10-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('cod_pending', 'เก็บเงินปลายทาง'), ('confirmed', 'ยืนยันแล้ว'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
